// examples/with-solid/apps/docs/src/components/Counter.tsx
import { createSignal } from "solid-js";
import "./Counter.css";
import { Button } from "@repo/ui";

export default function Counter() {
  const [count, setCount] = createSignal(0);
  return (
    <Button
      class=" bg-black text-white w-fit"
      onClick={() => setCount(count() + 1)}
      type="button">
      Docs Clicks: {count()}
    </Button>
  );
}

// examples/with-tailwind/packages/ui/src/client/counter.tsx
import { useState } from 'react'

export function Counter() {
  const [count, setCount] = useState(0)

  return (
    <div>
      <p>You clicked {count} times</p>
      <button className="ui-bg-neutral-500 ui-p-4 ui-rounded-lg ui-pointer-cursor ui-border-2 border-solid ui-border-neutral-300 hover:ui-bg-white hover:ui-text-neutral-500 ui-m-4 ui-mx-auto" onClick={() => setCount(count + 1)}>Click Me!!</button>
    </div>
  )
}
